import React,{useMemo,useState}from"react";
import{createRoot}from"react-dom/client";
import{Activity,ArrowDownRight,ArrowRight,ArrowUpRight,Bell,ChevronRight,LogOut,Search,ShieldCheck,X}from"lucide-react";
import"./styles.css";

const stocks=[
["NVDA","NVIDIA Corp.","Technology",151.42,31.84,"388.2M","$3.70T",[15,20,18,27,32,38,47,55,68,82]],["CRWV","CoreWeave Inc.","Technology",184.63,24.58,"34.9M","$89.4B",[10,17,15,24,30,35,44,50,60,74]],["IONQ","IonQ Inc.","Technology",44.18,21.09,"29.6M","$12.9B",[18,14,22,25,21,31,35,42,40,62]],["RKLB","Rocket Lab USA","Industrials",28.72,18.46,"41.3M","$14.5B",[14,20,18,22,30,27,36,41,45,58]],["PLTR","Palantir Technologies","Technology",142.10,12.36,"77.8M","$336B",[16,19,26,24,31,38,35,45,50,56]],["TSLA","Tesla Inc.","Consumer",326.43,10.62,"122.4M","$1.05T",[22,18,25,28,24,36,39,43,48,52]],["AMD","Advanced Micro Devices","Technology",127.85,7.82,"66.1M","$207B",[25,22,30,27,35,32,39,44,41,50]],["AAPL","Apple Inc.","Technology",204.09,5.18,"49.8M","$3.05T",[28,25,30,32,29,35,34,40,42,47]],["META","Meta Platforms","Communication",694.27,3.84,"18.2M","$1.75T",[22,25,24,29,27,31,34,32,38,41]],["UNH","UnitedHealth Group","Healthcare",294.75,-5.42,"19.1M","$267B",[65,61,62,55,57,48,45,39,35,31]],["BA","Boeing Co.","Industrials",188.40,-8.73,"13.6M","$142B",[70,64,67,59,56,52,48,42,39,33]],["COIN","Coinbase Global","Financial",236.82,-11.61,"17.3M","$59.8B",[75,71,67,64,59,54,50,44,39,34]],["MSTR","Strategy Inc.","Technology",368.14,-16.24,"21.8M","$103B",[82,76,79,69,65,59,55,48,42,36]],["SMCI","Super Micro Computer","Technology",37.65,-22.18,"58.4M","$22.3B",[85,80,76,72,65,60,54,48,40,32]],["WOLF","Wolfspeed Inc.","Technology",3.21,-34.64,"48.2M","$412M",[88,83,78,70,65,57,51,45,36,27]]
].map(([symbol,name,sector,price,change,volume,cap,spark])=>({symbol,name,sector,price,change,volume,cap,spark}));
const buckets=[["Up 5%+","up",5],["Down 5%+","down",5],["Up 10%+","up",10],["Down 10%+","down",10],["Up 20%+","up",20],["Down 20%+","down",20],["Up 30%+","up",30],["Down 30%+","down",30]].map(([label,dir,min])=>({label,dir,min}));
const match=(s,b)=>b.dir==="up"?s.change>=b.min:s.change<=-b.min;
function Spark({s,big=false}){let pts=s.spark.map((v,i)=>`${i*(big?42:9)},${100-v}`).join(" ");return <svg className={big?"spark big":"spark"} viewBox={big?"0 0 378 100":"0 0 81 100"} preserveAspectRatio="none"><polyline points={pts}/></svg>}
function Login({go}){return <div className="login"><section className="login-art"><Logo/><div><span className="eyebrow">US market intelligence</span><h1>Find stocks making <em>decisive moves.</em></h1><p>Track market breadth, explore percentage movers, and understand the price action behind every move.</p><div className="facts"><b>5,842<small>US stocks</small></b><b>8<small>drift buckets</small></b><b>Daily<small>market scans</small></b></div></div><small>Demo market data for product evaluation.</small></section><section className="login-side"><form onSubmit={e=>{e.preventDefault();go()}}><span className="eyebrow">Welcome back</span><h2>Sign in to your dashboard</h2><p>Use the demo credentials to explore today's market.</p><label>Email address<input type="email" defaultValue="demo@marketdrift.com"/></label><label>Password<input type="password" defaultValue="marketdemo"/></label><button className="primary">Open market dashboard <ArrowRight size={17}/></button><i><ShieldCheck size={15}/> Secure demo access</i></form></section></div>}
function Logo(){return <div className="logo"><span><Activity size={19}/></span>Market<b>Drift</b></div>}
function Detail({s,close}){return <div className="shade" onClick={close}><aside onClick={e=>e.stopPropagation()}><button className="close" onClick={close}><X/></button><span className="eyebrow">{s.sector}</span><div className="company"><i>{s.symbol.slice(0,2)}</i><div><h2>{s.symbol}</h2><p>{s.name}</p></div></div><div className="quote"><b>${s.price.toFixed(2)}</b><Move s={s}/></div><Spark s={s} big/><div className="metrics"><span>Market cap<b>{s.cap}</b></span><span>Volume<b>{s.volume}</b></span><span>Move bucket<b>{s.change>0?"Up":"Down"} {Math.floor(Math.abs(s.change)/5)*5}%+</b></span><span>Last updated<b>4:00 PM ET</b></span></div><button className="primary">View full company profile <ArrowRight size={16}/></button></aside></div>}
function Move({s}){return <span className={s.change>0?"move pos":"move neg"}>{s.change>0?"+":""}{s.change.toFixed(2)}%</span>}
function List({title,data,pick}){return <section className="panel list"><div className="panel-head"><div><h3>{title}</h3><p>Today's strongest market moves</p></div><button>View all <ArrowRight size={14}/></button></div>{data.map(s=><div className="row" onClick={()=>pick(s)} key={s.symbol}><i>{s.symbol.slice(0,2)}</i><span><b>{s.symbol}</b><small>{s.name}</small></span><Spark s={s}/><b>${s.price.toFixed(2)}</b><Move s={s}/><ChevronRight size={14}/></div>)}</section>}
function Dashboard({out}){const[query,setQuery]=useState(""),[bucket,setBucket]=useState(buckets[0]),[selected,setSelected]=useState();const filtered=useMemo(()=>stocks.filter(s=>match(s,bucket)&&`${s.symbol} ${s.name}`.toLowerCase().includes(query.toLowerCase())),[bucket,query]);const gain=[...stocks].filter(s=>s.change>0).sort((a,b)=>b.change-a.change).slice(0,5),loss=[...stocks].filter(s=>s.change<0).sort((a,b)=>a.change-b.change).slice(0,5);return <><header><Logo/><nav><b>Overview</b><span>Market breadth</span><span>Watchlists</span><span>Sectors</span></nav><div className="actions"><button><Bell size={17}/></button><button onClick={out}><i>DM</i><span>Demo User<small>Sign out</small></span><LogOut size={15}/></button></div></header><main><div className="hero"><div><span className="eyebrow">Thursday, June 11</span><h1>Market pulse</h1><p>See where momentum is building across US equities.</p></div><div className="status"><i/> Market closed <small>Next open in 16h 30m</small></div></div><div className="search"><Search size={19}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search stocks by symbol or company name..."/><kbd>⌘ K</kbd></div><div className="buckets">{buckets.map(b=>{let up=b.dir==="up";return <button className={`${up?"up":"down"} ${bucket.label===b.label?"on":""}`} onClick={()=>setBucket(b)} key={b.label}>{up?<ArrowUpRight/>:<ArrowDownRight/>}<span>{b.label}</span><b>{stocks.filter(s=>match(s,b)).length}</b><small>stocks today</small></button>})}</div><section className="panel breadth"><div className="panel-head"><div><h3>Market breadth</h3><p>Stock count distribution across daily price movements</p></div><span className="updated">● Updated 4:05 PM ET</span></div><div className="breadth-graph">{[38,52,43,64,58,75,69,83,78,90].map((v,i)=><i key={i} style={{height:`${v}%`}}/>)}{[18,25,20,36,27,42,34,49,40,55].map((v,i)=><b key={i} style={{height:`${v}%`}}/>)}</div><div className="dates"><span>May 29</span><span>Jun 02</span><span>Jun 05</span><span>Jun 08</span><span>Jun 11</span></div></section><div className="section-title"><div><span className="eyebrow">Active filter</span><h2>{bucket.label} movers</h2><p>{filtered.length} stocks match this movement threshold today.</p></div></div><div className="cards">{filtered.map(s=><button onClick={()=>setSelected(s)} key={s.symbol}><i>{s.symbol.slice(0,2)}</i><small>{s.sector}</small><h3>{s.symbol}</h3><p>{s.name}</p><div><b>${s.price.toFixed(2)}</b><Move s={s}/></div></button>)}</div><div className="columns"><List title="Top gainers" data={gain} pick={setSelected}/><List title="Top losers" data={loss} pick={setSelected}/></div></main><footer>MarketDrift demo <span>Data delayed · Built for analysis, not investment advice</span></footer>{selected&&<Detail s={selected} close={()=>setSelected()}/>}</>}
function App(){const[logged,setLogged]=useState(false);return logged?<Dashboard out={()=>setLogged(false)}/>:<Login go={()=>setLogged(true)}/>}createRoot(document.getElementById("root")).render(<App/>);
